# -*- coding: utf-8 -*-
import os

lines = []
def L(s): lines.append(s)

L("import 'dart:math';")
L("import 'package:flutter/material.dart';")
L("import '../data/puzzles.dart';")
L("import '../models/puzzle.dart';")
L("import '../services/score_service.dart';")
L("import '../widgets/bg_particles.dart';")
L("import '../widgets/tutorial_overlay.dart';")
L("import 'game_screen.dart';")
L("import 'settings_screen.dart';")
L("")
L("class HomeScreen extends StatefulWidget {")
L("  const HomeScreen({super.key});")
L("  @override")
L("  State<HomeScreen> createState() => _HomeScreenState();")
L("}")
L("")
L("class _HomeScreenState extends State<HomeScreen>")
L("    with SingleTickerProviderStateMixin {")
L("  late List<Puzzle> _allPuzzles;")
L("  int _filterIndex = 0;")
L("  Set<String> _completed = {};")
L("  Map<String, int> _bestTimes = {};")
L("  int _totalStars = 0;")
L("  int _easyDone = 0, _medDone = 0, _hardDone = 0;")
L("  int _easyTotal = 0, _medTotal = 0, _hardTotal = 0;")
L("  late AnimationController _titleCtrl;")
L("  late Animation<double> _titleAnim;")
L("")
L("  @override")
L("  void initState() {")
L("    super.initState();")
L("    _allPuzzles = getShuffledPuzzles();")
L("    _loadProgress();")
L("    _titleCtrl = AnimationController(vsync: this, duration: const Duration(seconds: 4))")
L("      ..repeat(reverse: true);")
L("    _titleAnim = Tween<double>(begin: 0.0, end: 1.0).animate(_titleCtrl);")
L("  }")
L("")
L("  @override")
L("  void dispose() {")
L("    _titleCtrl.dispose();")
L("    super.dispose();")
L("  }")
L("")
L("  Future<void> _loadProgress() async {")
L("    final completed = await ScoreService.getCompleted();")
L("    final Map<String, int> bests = {};")
L("    int totalStars = 0;")
L("    int easyDone = 0, medDone = 0, hardDone = 0;")
L("    int easyTotal = 0, medTotal = 0, hardTotal = 0;")
L("    for (final p in _allPuzzles) {")
L("      final c = p.pieceIds.length;")
L("      if (c <= 3) easyTotal++;")
L("      else if (c == 4) medTotal++;")
L("      else hardTotal++;")
L("      final b = await ScoreService.getBest(p.id);")
L("      if (b != null) {")
L("        bests[p.id] = b;")
L("        totalStars += ScoreService.calcStars(b, _timerFor(p));")
L("      }")
L("      if (completed.contains(p.id)) {")
L("        if (c <= 3) easyDone++;")
L("        else if (c == 4) medDone++;")
L("        else hardDone++;")
L("      }")
L("    }")
L("    if (mounted) setState(() {")
L("      _completed = completed;")
L("      _bestTimes = bests;")
L("      _totalStars = totalStars;")
L("      _easyDone = easyDone; _medDone = medDone; _hardDone = hardDone;")
L("      _easyTotal = easyTotal; _medTotal = medTotal; _hardTotal = hardTotal;")
L("    });")
L("  }")
L("")
L("  List<Puzzle> get _filtered {")
L("    switch (_filterIndex) {")
L("      case 1: return _allPuzzles.where((p) => p.pieceIds.length <= 3).toList();")
L("      case 2: return _allPuzzles.where((p) => p.pieceIds.length == 4).toList();")
L("      case 3: return _allPuzzles.where((p) => p.pieceIds.length >= 5).toList();")
L("      default: return _allPuzzles;")
L("    }")
L("  }")
L("")
L("  int _timerFor(Puzzle p) {")
L("    final c = p.pieceIds.length;")
L("    if (c <= 3) return 90;")
L("    if (c == 4) return 60;")
L("    return 45;")
L("  }")
L("")
L("  int _starsFor(Puzzle p) {")
L("    final best = _bestTimes[p.id];")
L("    if (best == null) return 0;")
L("    return ScoreService.calcStars(best, _timerFor(p));")
L("  }")
L("")
L("  void _startGame(Puzzle puzzle) {")
L("    final globalIndex = _allPuzzles.indexOf(puzzle);")
L("    Navigator.push(")
L("      context,")
L("      MaterialPageRoute(")
L("        builder: (_) => GameScreen(puzzles: _allPuzzles, initialIndex: globalIndex),")
L("      ),")
L("    ).then((_) => _loadProgress());")
L("  }")

L("  @override")
L("  Widget build(BuildContext context) {")
L("    final filtered = _filtered;")
L("    final total = _allPuzzles.length;")
L("    final done = _completed.length;")
L("    final pct = total > 0 ? done / total : 0.0;")
L("    return Scaffold(")
L("      backgroundColor: const Color(0xFF0D0D1A),")
L("      body: TutorialOverlay(")
L("        child: Stack(")
L("          children: [")
L("            const Positioned.fill(child: BgParticles()),")
L("            Positioned(")
L("              top: 0, left: 0, right: 0, height: 280,")
L("              child: DecoratedBox(")
L("                decoration: BoxDecoration(")
L("                  gradient: LinearGradient(")
L("                    begin: Alignment.topCenter,")
L("                    end: Alignment.bottomCenter,")
L("                    colors: [")
L("                      const Color(0xFF1A1A3E).withValues(alpha: 0.95),")
L("                      Colors.transparent,")
L("                    ],")
L("                  ),")
L("                ),")
L("              ),")
L("            ),")
L("            SafeArea(")
L("              child: Column(")
L("                children: [")
L("                  _buildHeader(),")
L("                  _buildTitleSection(),")
L("                  _buildProgressSection(done, total, pct),")
L("                  const SizedBox(height: 10),")
L("                  _buildFilterRow(),")
L("                  const SizedBox(height: 6),")
L("                  Expanded(child: _buildPuzzleList(filtered)),")
L("                ],")
L("              ),")
L("            ),")
L("          ],")
L("        ),")
L("      ),")
L("    );")
L("  }")
L("")
L("  Widget _buildHeader() {")
L("    return Padding(")
L("      padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),")
L("      child: Row(")
L("        mainAxisAlignment: MainAxisAlignment.spaceBetween,")
L("        children: [")
L("          AnimatedBuilder(")
L("            animation: _titleAnim,")
L("            builder: (_, __) => Container(")
L("              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7),")
L("              decoration: BoxDecoration(")
L("                gradient: LinearGradient(colors: [")
L("                  Colors.amber.withValues(alpha: 0.25 + _titleAnim.value * 0.1),")
L("                  Colors.orange.withValues(alpha: 0.15),")
L("                ]),")
L("                borderRadius: BorderRadius.circular(24),")
L("                border: Border.all(")
L("                  color: Colors.amber.withValues(alpha: 0.4 + _titleAnim.value * 0.2),")
L("                  width: 1.5,")
L("                ),")
L("                boxShadow: [BoxShadow(")
L("                  color: Colors.amber.withValues(alpha: 0.15 + _titleAnim.value * 0.1),")
L("                  blurRadius: 12, spreadRadius: 1,")
L("                )],")
L("              ),")
L("              child: Row(")
L("                mainAxisSize: MainAxisSize.min,")
L("                children: [")
L("                  const Icon(Icons.star_rounded, color: Colors.amber, size: 18),")
L("                  const SizedBox(width: 5),")
L("                  Text(")
L("                    '$_totalStars / ${_allPuzzles.length * 3}',")
L("                    style: const TextStyle(color: Colors.amber, fontSize: 14, fontWeight: FontWeight.bold),")
L("                  ),")
L("                ],")
L("              ),")
L("            ),")
L("          ),")
L("          GestureDetector(")
L("            onTap: () => Navigator.push(")
L("              context,")
L("              MaterialPageRoute(builder: (_) => const SettingsScreen()),")
L("            ).then((_) => _loadProgress()),")
L("            child: Container(")
L("              width: 40, height: 40,")
L("              decoration: BoxDecoration(")
L("                color: Colors.white.withValues(alpha: 0.08),")
L("                shape: BoxShape.circle,")
L("                border: Border.all(color: Colors.white24),")
L("              ),")
L("              child: const Icon(Icons.settings_rounded, color: Colors.white60, size: 20),")
L("            ),")
L("          ),")
L("        ],")
L("      ),")
L("    );")
L("  }")

L("  Widget _buildTitleSection() {")
L("    return Padding(")
L("      padding: const EdgeInsets.symmetric(vertical: 12),")
L("      child: Column(")
L("        children: [")
L("          AnimatedBuilder(")
L("            animation: _titleAnim,")
L("            builder: (_, __) => ShaderMask(")
L("              shaderCallback: (bounds) => LinearGradient(")
L("                colors: [")
L("                  const Color(0xFF4D96FF),")
L("                  Color.lerp(const Color(0xFF9B59FF), const Color(0xFF4DFFB4), _titleAnim.value)!,")
L("                  const Color(0xFF4D96FF),")
L("                ],")
L("                stops: const [0.0, 0.5, 1.0],")
L("              ).createShader(bounds),")
L("              child: const Text(")
L("                '\uBE14\uB85D\uD53C\uD2B8',")
L("                style: TextStyle(color: Colors.white, fontSize: 46, fontWeight: FontWeight.w900, letterSpacing: 3),")
L("              ),")
L("            ),")
L("          ),")
L("          const SizedBox(height: 4),")
L("          Text(")
L("            '\uC870\uAC01\uC744 \uB9DE\uCDB0 \uBCF4\uB4DC\uB97C \uCC44\uC6B0\uC138\uC694',")
L("            style: TextStyle(color: Colors.white.withValues(alpha: 0.45), fontSize: 14),")
L("          ),")
L("        ],")
L("      ),")
L("    );")
L("  }")
L("")
L("  Widget _buildProgressSection(int done, int total, double pct) {")
L("    return Padding(")
L("      padding: const EdgeInsets.symmetric(horizontal: 20),")
L("      child: Container(")
L("        padding: const EdgeInsets.all(16),")
L("        decoration: BoxDecoration(")
L("          color: Colors.white.withValues(alpha: 0.05),")
L("          borderRadius: BorderRadius.circular(20),")
L("          border: Border.all(color: Colors.white.withValues(alpha: 0.08)),")
L("        ),")
L("        child: Row(")
L("          children: [")
L("            SizedBox(")
L("              width: 64, height: 64,")
L("              child: CustomPaint(")
L("                painter: _CircleProgressPainter(pct),")
L("                child: Center(")
L("                  child: Text(")
L("                    '${(pct * 100).round()}%',")
L("                    style: const TextStyle(color: Colors.white, fontSize: 13, fontWeight: FontWeight.bold),")
L("                  ),")
L("                ),")
L("              ),")
L("            ),")
L("            const SizedBox(width: 16),")
L("            Expanded(")
L("              child: Column(")
L("                crossAxisAlignment: CrossAxisAlignment.start,")
L("                children: [")
L("                  Row(")
L("                    mainAxisAlignment: MainAxisAlignment.spaceBetween,")
L("                    children: [")
L("                      Text('\uC804\uCCB4 \uC9C4\uD589\uB960', style: TextStyle(color: Colors.white.withValues(alpha: 0.6), fontSize: 12)),")
L("                      Text('$done / $total \uC644\uB8CC', style: const TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold)),")
L("                    ],")
L("                  ),")
L("                  const SizedBox(height: 10),")
L("                  Row(")
L("                    children: [")
L("                      _DiffBar(label: '\uC27D\uC74C', done: _easyDone, total: _easyTotal, color: const Color(0xFF6BCB77)),")
L("                      const SizedBox(width: 8),")
L("                      _DiffBar(label: '\uBCF4\uD1B5', done: _medDone, total: _medTotal, color: const Color(0xFFFF922B)),")
L("                      const SizedBox(width: 8),")
L("                      _DiffBar(label: '\uC5B4\uB824\uC6C0', done: _hardDone, total: _hardTotal, color: const Color(0xFFFF6B6B)),")
L("                    ],")
L("                  ),")
L("                ],")
L("              ),")
L("            ),")
L("          ],")
L("        ),")
L("      ),")
L("    );")
L("  }")
L("")
L("  Widget _buildFilterRow() {")
L("    final labels = ['\uC804\uCCB4', '\uC27D\uC74C', '\uBCF4\uD1B5', '\uC5B4\uB824\uC6C0'];")
L("    final colors = [Colors.white70, const Color(0xFF6BCB77), const Color(0xFFFF922B), const Color(0xFFFF6B6B)];")
L("    return Row(")
L("      mainAxisAlignment: MainAxisAlignment.center,")
L("      children: [")
L("        ...List.generate(labels.length, (i) => Padding(")
L("          padding: EdgeInsets.only(left: i == 0 ? 0 : 8),")
L("          child: _FilterChip(")
L("            label: labels[i], selected: _filterIndex == i,")
L("            color: colors[i], onTap: () => setState(() => _filterIndex = i),")
L("          ),")
L("        )),")
L("        const SizedBox(width: 8),")
L("        GestureDetector(")
L("          onTap: () => setState(() => _allPuzzles = getShuffledPuzzles()),")
L("          child: Container(")
L("            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),")
L("            decoration: BoxDecoration(")
L("              color: Colors.blueAccent.withValues(alpha: 0.12),")
L("              borderRadius: BorderRadius.circular(20),")
L("              border: Border.all(color: Colors.blueAccent.withValues(alpha: 0.3)),")
L("            ),")
L("            child: const Icon(Icons.shuffle_rounded, color: Colors.blueAccent, size: 16),")
L("          ),")
L("        ),")
L("      ],")
L("    );")
L("  }")
L("")
L("  Widget _buildPuzzleList(List<Puzzle> filtered) {")
L("    return ListView.builder(")
L("      padding: const EdgeInsets.fromLTRB(16, 4, 16, 16),")
L("      itemCount: filtered.length,")
L("      itemBuilder: (context, i) {")
L("        final puzzle = filtered[i];")
L("        final count = puzzle.pieceIds.length;")
L("        final isEasy = count <= 3;")
L("        final isHard = count >= 5;")
L("        final isCleared = _completed.contains(puzzle.id);")
L("        final stars = _starsFor(puzzle);")
L("        return _PuzzleCard(")
L("          index: i + 1, puzzle: puzzle, isEasy: isEasy, isHard: isHard,")
L("          isCleared: isCleared, stars: stars, onTap: () => _startGame(puzzle),")
L("        );")
L("      },")
L("    );")
L("  }")
L("}")

L("")
L("class _CircleProgressPainter extends CustomPainter {")
L("  final double value;")
L("  _CircleProgressPainter(this.value);")
L("  @override")
L("  void paint(Canvas canvas, Size size) {")
L("    final cx = size.width / 2;")
L("    final cy = size.height / 2;")
L("    final r = (size.width - 10) / 2;")
L("    canvas.drawCircle(Offset(cx, cy), r, Paint()")
L("      ..color = Colors.white.withValues(alpha: 0.08)")
L("      ..style = PaintingStyle.stroke ..strokeWidth = 6);")
L("    final rect = Rect.fromCircle(center: Offset(cx, cy), radius: r);")
L("    canvas.drawArc(rect, -pi / 2, 2 * pi * value, false, Paint()")
L("      ..shader = LinearGradient(")
L("        colors: const [Color(0xFF4D96FF), Color(0xFF4DFFB4)],")
L("        begin: Alignment.topCenter, end: Alignment.bottomCenter,")
L("      ).createShader(rect)")
L("      ..style = PaintingStyle.stroke ..strokeWidth = 6 ..strokeCap = StrokeCap.round);")
L("  }")
L("  @override")
L("  bool shouldRepaint(_CircleProgressPainter old) => old.value != value;")
L("}")
L("")
L("class _DiffBar extends StatelessWidget {")
L("  final String label;")
L("  final int done, total;")
L("  final Color color;")
L("  const _DiffBar({required this.label, required this.done, required this.total, required this.color});")
L("  @override")
L("  Widget build(BuildContext context) {")
L("    final ratio = total > 0 ? done / total : 0.0;")
L("    return Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
L("      Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [")
L("        Text(label, style: TextStyle(color: color, fontSize: 10, fontWeight: FontWeight.bold)),")
L("        Text('$done/$total', style: TextStyle(color: color.withValues(alpha: 0.6), fontSize: 10)),")
L("      ]),")
L("      const SizedBox(height: 4),")
L("      ClipRRect(borderRadius: BorderRadius.circular(4), child: Stack(children: [")
L("        Container(height: 6, color: Colors.white.withValues(alpha: 0.07)),")
L("        FractionallySizedBox(widthFactor: ratio, child: Container(")
L("          height: 6,")
L("          decoration: BoxDecoration(")
L("            gradient: LinearGradient(colors: [color.withValues(alpha: 0.7), color]),")
L("            borderRadius: BorderRadius.circular(4),")
L("          ),")
L("        )),")
L("      ])),")
L("    ]));")
L("  }")
L("}")
L("")
L("class _FilterChip extends StatelessWidget {")
L("  final String label;")
L("  final bool selected;")
L("  final Color color;")
L("  final VoidCallback onTap;")
L("  const _FilterChip({required this.label, required this.selected, required this.color, required this.onTap});")
L("  @override")
L("  Widget build(BuildContext context) {")
L("    return GestureDetector(")
L("      onTap: onTap,")
L("      child: AnimatedContainer(")
L("        duration: const Duration(milliseconds: 200),")
L("        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7),")
L("        decoration: BoxDecoration(")
L("          color: selected ? color.withValues(alpha: 0.18) : Colors.transparent,")
L("          borderRadius: BorderRadius.circular(20),")
L("          border: Border.all(color: selected ? color : Colors.white.withValues(alpha: 0.15), width: selected ? 1.5 : 1),")
L("          boxShadow: selected ? [BoxShadow(color: color.withValues(alpha: 0.25), blurRadius: 8)] : [],")
L("        ),")
L("        child: Text(label, style: TextStyle(")
L("          color: selected ? color : Colors.white.withValues(alpha: 0.35),")
L("          fontSize: 13, fontWeight: selected ? FontWeight.bold : FontWeight.normal,")
L("        )),")
L("      ),")
L("    );")
L("  }")
L("}")
L("")
L("class _PuzzleCard extends StatefulWidget {")
L("  final int index;")
L("  final Puzzle puzzle;")
L("  final bool isEasy, isHard, isCleared;")
L("  final int stars;")
L("  final VoidCallback onTap;")
L("  const _PuzzleCard({required this.index, required this.puzzle, required this.isEasy,")
L("    required this.isHard, required this.isCleared, required this.stars, required this.onTap});")
L("  @override")
L("  State<_PuzzleCard> createState() => _PuzzleCardState();")
L("}")
L("")
L("class _PuzzleCardState extends State<_PuzzleCard> {")
L("  bool _pressed = false;")
L("  @override")
L("  Widget build(BuildContext context) {")
L("    final diffColor = widget.isEasy ? const Color(0xFF6BCB77) : widget.isHard ? const Color(0xFFFF6B6B) : const Color(0xFFFF922B);")
L("    final diffLabel = widget.isEasy ? '\uC27D\uC74C' : widget.isHard ? '\uC5B4\uB824\uC6C0' : '\uBCF4\uD1B5';")
L("    return GestureDetector(")
L("      onTapDown: (_) => setState(() => _pressed = true),")
L("      onTapUp: (_) { setState(() => _pressed = false); widget.onTap(); },")
L("      onTapCancel: () => setState(() => _pressed = false),")
L("      child: AnimatedContainer(")
L("        duration: const Duration(milliseconds: 120),")
L("        margin: const EdgeInsets.only(bottom: 10),")
L("        transform: Matrix4.identity()..scale(_pressed ? 0.97 : 1.0),")
L("        decoration: BoxDecoration(")
L("          gradient: LinearGradient(")
L("            begin: Alignment.topLeft, end: Alignment.bottomRight,")
L("            colors: widget.isCleared")
L("                ? [const Color(0xFF1A2E20), const Color(0xFF0F1F14)]")
L("                : [const Color(0xFF1C2340), const Color(0xFF111828)],")
L("          ),")
L("          borderRadius: BorderRadius.circular(18),")
L("          border: Border.all(")
L("            color: widget.isCleared ? const Color(0xFF6BCB77).withValues(alpha: 0.35) : Colors.white.withValues(alpha: 0.08),")
L("            width: 1.5,")
L("          ),")
L("          boxShadow: [BoxShadow(")
L("            color: widget.isCleared ? const Color(0xFF6BCB77).withValues(alpha: 0.08) : Colors.black.withValues(alpha: 0.3),")
L("            blurRadius: 12, offset: const Offset(0, 4),")
L("          )],")
L("        ),")
L("        child: Padding(")
L("          padding: const EdgeInsets.all(14),")
L("          child: Row(children: [")
L("            _MiniBoardPreview(puzzle: widget.puzzle, isCleared: widget.isCleared, diffColor: diffColor),")
L("            const SizedBox(width: 14),")
L("            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
L("              Row(children: [")
L("                Text('\uD37C\uC990 ${widget.index}', style: const TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold)),")
L("                const Spacer(),")
L("                if (widget.isCleared) Container(")
L("                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),")
L("                  decoration: BoxDecoration(")
L("                    color: const Color(0xFF6BCB77).withValues(alpha: 0.15),")
L("                    borderRadius: BorderRadius.circular(10),")
L("                    border: Border.all(color: const Color(0xFF6BCB77).withValues(alpha: 0.4)),")
L("                  ),")
L("                  child: const Row(mainAxisSize: MainAxisSize.min, children: [")
L("                    Icon(Icons.check_rounded, color: Color(0xFF6BCB77), size: 11),")
L("                    SizedBox(width: 3),")
L("                    Text('\uC644\uB8CC', style: TextStyle(color: Color(0xFF6BCB77), fontSize: 10, fontWeight: FontWeight.bold)),")
L("                  ]),")
L("                ),")
L("              ]),")
L("              const SizedBox(height: 4),")
L("              Row(children: [")
L("                Container(")
L("                  padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),")
L("                  decoration: BoxDecoration(color: diffColor.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(8)),")
L("                  child: Text(diffLabel, style: TextStyle(color: diffColor, fontSize: 11, fontWeight: FontWeight.bold)),")
L("                ),")
L("                const SizedBox(width: 8),")
L("                Text('${widget.puzzle.rows}x${widget.puzzle.cols}  \u00B7  \uC870\uAC01 ${widget.puzzle.pieceIds.length}\uAC1C',")
L("                  style: TextStyle(color: Colors.white.withValues(alpha: 0.4), fontSize: 12)),")
L("              ]),")
L("              if (widget.isCleared && widget.stars > 0) ...[")
L("                const SizedBox(height: 6),")
L("                Row(children: List.generate(3, (i) => Padding(")
L("                  padding: const EdgeInsets.only(right: 2),")
L("                  child: Icon(")
L("                    i < widget.stars ? Icons.star_rounded : Icons.star_outline_rounded,")
L("                    color: i < widget.stars ? Colors.amber : Colors.white24, size: 16,")
L("                  ),")
L("                ))),")
L("              ],")
L("            ])),")
L("            const SizedBox(width: 8),")
L("            Icon(Icons.chevron_right_rounded, color: Colors.white.withValues(alpha: 0.25), size: 22),")
L("          ]),")
L("        ),")
L("      ),")
L("    );")
L("  }")
L("}")
L("")
L("class _MiniBoardPreview extends StatelessWidget {")
L("  final Puzzle puzzle;")
L("  final bool isCleared;")
L("  final Color diffColor;")
L("  const _MiniBoardPreview({required this.puzzle, required this.isCleared, required this.diffColor});")
L("  @override")
L("  Widget build(BuildContext context) {")
L("    const sz = 58.0;")
L("    final cs = (sz / (puzzle.rows > puzzle.cols ? puzzle.rows : puzzle.cols)).clamp(4.0, 12.0);")
L("    return Container(")
L("      width: sz, height: sz,")
L("      decoration: BoxDecoration(")
L("        color: const Color(0xFF080E1A),")
L("        borderRadius: BorderRadius.circular(12),")
L("        border: Border.all(")
L("          color: isCleared ? const Color(0xFF6BCB77).withValues(alpha: 0.4) : Colors.white.withValues(alpha: 0.08),")
L("          width: 1.5,")
L("        ),")
L("        boxShadow: [BoxShadow(color: (isCleared ? const Color(0xFF6BCB77) : diffColor).withValues(alpha: 0.12), blurRadius: 8)],")
L("      ),")
L("      child: Center(child: CustomPaint(")
L("        size: Size(cs * puzzle.cols, cs * puzzle.rows),")
L("        painter: _MiniBoardPainter(puzzle, isCleared, diffColor, cs),")
L("      )),")
L("    );")
L("  }")
L("}")
L("")
L("class _MiniBoardPainter extends CustomPainter {")
L("  final Puzzle puzzle;")
L("  final bool isCleared;")
L("  final Color diffColor;")
L("  final double cs;")
L("  _MiniBoardPainter(this.puzzle, this.isCleared, this.diffColor, this.cs);")
L("  @override")
L("  void paint(Canvas canvas, Size size) {")
L("    const gap = 1.0;")
L("    for (int r = 0; r < puzzle.rows; r++) {")
L("      for (int c = 0; c < puzzle.cols; c++) {")
L("        final active = puzzle.grid[r][c];")
L("        final rect = RRect.fromRectAndRadius(")
L("          Rect.fromLTWH(c * cs + gap, r * cs + gap, cs - gap * 2, cs - gap * 2),")
L("          Radius.circular(cs * 0.25),")
L("        );")
L("        if (active) {")
L("          canvas.drawRRect(rect, Paint()..shader = LinearGradient(")
L("            begin: Alignment.topLeft, end: Alignment.bottomRight,")
L("            colors: isCleared ? [const Color(0xFF6BCB77), const Color(0xFF20C997)]")
L("                : [diffColor.withValues(alpha: 0.9), diffColor.withValues(alpha: 0.5)],")
L("          ).createShader(Rect.fromLTWH(c * cs, r * cs, cs, cs)));")
L("          canvas.drawRRect(")
L("            RRect.fromRectAndRadius(Rect.fromLTWH(c * cs + gap, r * cs + gap, cs - gap * 2, 2), Radius.circular(cs * 0.25)),")
L("            Paint()..color = Colors.white.withValues(alpha: 0.3),")
L("          );")
L("        } else {")
L("          canvas.drawRRect(rect, Paint()..color = Colors.white.withValues(alpha: 0.04));")
L("        }")
L("      }")
L("    }")
L("  }")
L("  @override")
L("  bool shouldRepaint(_MiniBoardPainter old) => false;")
L("}")

content = '\n'.join(lines) + '\n'
with open('lib/screens/home_screen.dart', 'w', encoding='utf-8') as f:
    f.write(content)

with open('lib/screens/home_screen.dart', 'r', encoding='utf-8') as f:
    c = f.read()
print('Lines:', len(c.splitlines()))
print('Has BgParticles:', 'BgParticles' in c)
print('Has SettingsScreen:', 'SettingsScreen' in c)
print('Has TutorialOverlay:', 'TutorialOverlay' in c)
print('Has dart:math:', 'dart:math' in c)
print('Braces:', c.count('{'), '/', c.count('}'))
