# -*- coding: utf-8 -*-
lines = [
    "import 'package:flutter/material.dart';",
    "import '../data/puzzles.dart';",
    "import '../models/puzzle.dart';",
    "import 'game_screen.dart';",
    "",
    "class HomeScreen extends StatefulWidget {",
    "  const HomeScreen({super.key});",
    "",
    "  @override",
    "  State<HomeScreen> createState() => _HomeScreenState();",
    "}",
    "",
    "class _HomeScreenState extends State<HomeScreen> {",
    "  late List<Puzzle> _puzzles;",
    "",
    "  @override",
    "  void initState() {",
    "    super.initState();",
    "    _puzzles = getShuffledPuzzles();",
    "  }",
    "",
    "  void _reshuffle() {",
    "    setState(() => _puzzles = getShuffledPuzzles());",
    "  }",
    "",
    "  void _startGame(int index) {",
    "    Navigator.push(",
    "      context,",
    "      MaterialPageRoute(",
    "        builder: (_) => GameScreen(",
    "          puzzles: _puzzles,",
    "          initialIndex: index,",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Scaffold(",
    "      backgroundColor: const Color(0xFF1A1A2E),",
    "      body: SafeArea(",
    "        child: Column(",
    "          children: [",
    "            const SizedBox(height: 48),",
    "            const Text(",
    "              '\ube14\ub85d\ud53c\ud2b8',",
    "              style: TextStyle(",
    "                color: Colors.white,",
    "                fontSize: 48,",
    "                fontWeight: FontWeight.bold,",
    "                letterSpacing: 2,",
    "              ),",
    "            ),",
    "            const SizedBox(height: 8),",
    "            const Text(",
    "              '\uc870\uac01\uc744 \ub9de\ucdb0 \ubcf4\ub4dc\ub97c \ucc44\uc6b0\uc138\uc694!',",
    "              style: TextStyle(color: Colors.white54, fontSize: 16),",
    "            ),",
    "            const SizedBox(height: 16),",
    "            TextButton.icon(",
    "              onPressed: _reshuffle,",
    "              icon: const Icon(Icons.shuffle, color: Colors.blueAccent),",
    "              label: const Text('\uc21c\uc11c \uc12d\uae30',",
    "                  style: TextStyle(color: Colors.blueAccent)),",
    "            ),",
    "            const SizedBox(height: 8),",
    "            Expanded(",
    "              child: ListView.builder(",
    "                padding: const EdgeInsets.symmetric(horizontal: 24),",
    "                itemCount: _puzzles.length,",
    "                itemBuilder: (context, i) {",
    "                  final puzzle = _puzzles[i];",
    "                  final isEasy = puzzle.pieceIds.length <= 3;",
    "                  return _PuzzleCard(",
    "                    index: i + 1,",
    "                    puzzle: puzzle,",
    "                    isEasy: isEasy,",
    "                    onTap: () => _startGame(i),",
    "                  );",
    "                },",
    "              ),",
    "            ),",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class _PuzzleCard extends StatelessWidget {",
    "  final int index;",
    "  final Puzzle puzzle;",
    "  final bool isEasy;",
    "  final VoidCallback onTap;",
    "",
    "  const _PuzzleCard({",
    "    required this.index,",
    "    required this.puzzle,",
    "    required this.isEasy,",
    "    required this.onTap,",
    "  });",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final diffColor = isEasy ? Colors.greenAccent : Colors.orangeAccent;",
    "    final diffLabel = isEasy ? '\uc27d\uc74c' : '\ubcf4\ud1b5';",
    "",
    "    return GestureDetector(",
    "      onTap: onTap,",
    "      child: Container(",
    "        margin: const EdgeInsets.only(bottom: 12),",
    "        padding: const EdgeInsets.all(16),",
    "        decoration: BoxDecoration(",
    "          color: const Color(0xFF16213E),",
    "          borderRadius: BorderRadius.circular(16),",
    "          border: Border.all(color: Colors.white12),",
    "        ),",
    "        child: Row(",
    "          children: [",
    "            Container(",
    "              width: 48,",
    "              height: 48,",
    "              decoration: BoxDecoration(",
    "                color: Colors.blueAccent.withValues(alpha: 0.2),",
    "                borderRadius: BorderRadius.circular(12),",
    "              ),",
    "              child: Center(",
    "                child: Text(",
    "                  '$index',",
    "                  style: const TextStyle(",
    "                    color: Colors.blueAccent,",
    "                    fontSize: 22,",
    "                    fontWeight: FontWeight.bold,",
    "                  ),",
    "                ),",
    "              ),",
    "            ),",
    "            const SizedBox(width: 16),",
    "            Column(",
    "              crossAxisAlignment: CrossAxisAlignment.start,",
    "              children: [",
    "                Text(",
    "                  '\ud37c\uc990 $index',",
    "                  style: const TextStyle(",
    "                      color: Colors.white,",
    "                      fontSize: 16,",
    "                      fontWeight: FontWeight.bold),",
    "                ),",
    "                Row(",
    "                  children: [",
    "                    Text(",
    "                      '${puzzle.rows}x${puzzle.cols}  |  \uc870\uac01 ${puzzle.pieceIds.length}\uac1c  |  ',",
    "                      style: const TextStyle(color: Colors.white54, fontSize: 13),",
    "                    ),",
    "                    Text(diffLabel,",
    "                        style: TextStyle(color: diffColor, fontSize: 13)),",
    "                  ],",
    "                ),",
    "              ],",
    "            ),",
    "            const Spacer(),",
    "            const Icon(Icons.arrow_forward_ios, color: Colors.white38, size: 16),",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
]

content = "\n".join(lines) + "\n"

with open('lib/screens/home_screen.dart', 'w', encoding='utf-8') as f:
    f.write(content)

with open('lib/screens/home_screen.dart', 'r', encoding='utf-8') as f:
    c = f.read()
print(f"Lines: {len(c.splitlines())}")
print(f"Open braces: {c.count(chr(123))}, Close braces: {c.count(chr(125))}")
print("Last 3 lines:", c.splitlines()[-3:])
