# -*- coding: utf-8 -*-
import re

lines = []
lines.append("import 'package:flutter/material.dart';")
lines.append("import '../data/puzzles.dart';")
lines.append("import '../models/puzzle.dart';")
lines.append("import 'game_screen.dart';")
lines.append("")
lines.append("class HomeScreen extends StatefulWidget {")
lines.append("  const HomeScreen({super.key});")
lines.append("  @override")
lines.append("  State<HomeScreen> createState() => _HomeScreenState();")
lines.append("}")
lines.append("")
lines.append("class _HomeScreenState extends State<HomeScreen> {")
lines.append("  late List<Puzzle> _allPuzzles;")
lines.append("  int _filterIndex = 0;")
lines.append("")
lines.append("  @override")
lines.append("  void initState() {")
lines.append("    super.initState();")
lines.append("    _allPuzzles = getShuffledPuzzles();")
lines.append("  }")
lines.append("")
lines.append("  List<Puzzle> get _filtered {")
lines.append("    switch (_filterIndex) {")
lines.append("      case 1: return _allPuzzles.where((p) => p.pieceIds.length <= 3).toList();")
lines.append("      case 2: return _allPuzzles.where((p) => p.pieceIds.length == 4).toList();")
lines.append("      case 3: return _allPuzzles.where((p) => p.pieceIds.length >= 5).toList();")
lines.append("      default: return _allPuzzles;")
lines.append("    }")
lines.append("  }")
lines.append("")
lines.append("  void _startGame(Puzzle puzzle) {")
lines.append("    final globalIndex = _allPuzzles.indexOf(puzzle);")
lines.append("    Navigator.push(")
lines.append("      context,")
lines.append("      MaterialPageRoute(")
lines.append("        builder: (_) => GameScreen(")
lines.append("          puzzles: _allPuzzles,")
lines.append("          initialIndex: globalIndex,")
lines.append("        ),")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  @override")
lines.append("  Widget build(BuildContext context) {")
lines.append("    final filtered = _filtered;")
lines.append("    return Scaffold(")
lines.append("      backgroundColor: const Color(0xFF1A1A2E),")
lines.append("      body: SafeArea(")
lines.append("        child: Column(")
lines.append("          children: [")
lines.append("            const SizedBox(height: 32),")
lines.append("            const Text(")
lines.append("              '\uBE14\uB85D\uD53C\uD2B8',")
lines.append("              style: TextStyle(")
lines.append("                color: Colors.white,")
lines.append("                fontSize: 48,")
lines.append("                fontWeight: FontWeight.bold,")
lines.append("                letterSpacing: 2,")
lines.append("              ),")
lines.append("            ),")
lines.append("            const SizedBox(height: 8),")
lines.append("            const Text(")
lines.append("              '\uC870\uAC01\uC744 \uB9DE\uCDB0 \uBCF4\uB4DC\uB97C \uCC44\uC6B0\uC138\uC694!',")
lines.append("              style: TextStyle(color: Colors.white54, fontSize: 16),")
lines.append("            ),")
lines.append("            const SizedBox(height: 12),")
lines.append("            Row(")
lines.append("              mainAxisAlignment: MainAxisAlignment.center,")
lines.append("              children: [")
lines.append("                _FilterTab(label: '\uC804\uCCB4', selected: _filterIndex == 0,")
lines.append("                    color: Colors.white70, onTap: () => setState(() => _filterIndex = 0)),")
lines.append("                const SizedBox(width: 8),")
lines.append("                _FilterTab(label: '\uC27D\uC74C', selected: _filterIndex == 1,")
lines.append("                    color: Colors.greenAccent, onTap: () => setState(() => _filterIndex = 1)),")
lines.append("                const SizedBox(width: 8),")
lines.append("                _FilterTab(label: '\uBCF4\uD1B5', selected: _filterIndex == 2,")
lines.append("                    color: Colors.orangeAccent, onTap: () => setState(() => _filterIndex = 2)),")
lines.append("                const SizedBox(width: 8),")
lines.append("                _FilterTab(label: '\uC5B4\uB824\uC6C0', selected: _filterIndex == 3,")
lines.append("                    color: Colors.redAccent, onTap: () => setState(() => _filterIndex = 3)),")
lines.append("              ],")
lines.append("            ),")
lines.append("            const SizedBox(height: 4),")
lines.append("            TextButton.icon(")
lines.append("              onPressed: () => setState(() => _allPuzzles = getShuffledPuzzles()),")
lines.append("              icon: const Icon(Icons.shuffle, color: Colors.blueAccent, size: 16),")
lines.append("              label: const Text('\uC21C\uC11C \uC12D\uAE30',")
lines.append("                  style: TextStyle(color: Colors.blueAccent, fontSize: 13)),")
lines.append("            ),")
lines.append("            Expanded(")
lines.append("              child: ListView.builder(")
lines.append("                padding: const EdgeInsets.symmetric(horizontal: 24),")
lines.append("                itemCount: filtered.length,")
lines.append("                itemBuilder: (context, i) {")
lines.append("                  final puzzle = filtered[i];")
lines.append("                  final count = puzzle.pieceIds.length;")
lines.append("                  final isEasy = count <= 3;")
lines.append("                  final isHard = count >= 5;")
lines.append("                  return _PuzzleCard(")
lines.append("                    index: i + 1,")
lines.append("                    puzzle: puzzle,")
lines.append("                    isEasy: isEasy,")
lines.append("                    isHard: isHard,")
lines.append("                    onTap: () => _startGame(puzzle),")
lines.append("                  );")
lines.append("                },")
lines.append("              ),")
lines.append("            ),")
lines.append("          ],")
lines.append("        ),")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("class _FilterTab extends StatelessWidget {")
lines.append("  final String label;")
lines.append("  final bool selected;")
lines.append("  final Color color;")
lines.append("  final VoidCallback onTap;")
lines.append("  const _FilterTab({required this.label, required this.selected, required this.color, required this.onTap});")
lines.append("  @override")
lines.append("  Widget build(BuildContext context) {")
lines.append("    return GestureDetector(")
lines.append("      onTap: onTap,")
lines.append("      child: Container(")
lines.append("        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),")
lines.append("        decoration: BoxDecoration(")
lines.append("          color: selected ? color.withValues(alpha: 0.2) : Colors.transparent,")
lines.append("          borderRadius: BorderRadius.circular(20),")
lines.append("          border: Border.all(color: selected ? color : Colors.white24, width: selected ? 1.5 : 1),")
lines.append("        ),")
lines.append("        child: Text(label,")
lines.append("          style: TextStyle(")
lines.append("            color: selected ? color : Colors.white38,")
lines.append("            fontSize: 13,")
lines.append("            fontWeight: selected ? FontWeight.bold : FontWeight.normal,")
lines.append("          ),")
lines.append("        ),")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("class _PuzzleCard extends StatelessWidget {")
lines.append("  final int index;")
lines.append("  final Puzzle puzzle;")
lines.append("  final bool isEasy;")
lines.append("  final bool isHard;")
lines.append("  final VoidCallback onTap;")
lines.append("  const _PuzzleCard({required this.index, required this.puzzle, required this.isEasy, required this.isHard, required this.onTap});")
lines.append("  @override")
lines.append("  Widget build(BuildContext context) {")
lines.append("    final diffColor = isEasy ? Colors.greenAccent : isHard ? Colors.redAccent : Colors.orangeAccent;")
lines.append("    final diffLabel = isEasy ? '\uC27D\uC74C' : isHard ? '\uC5B4\uB824\uC6C0' : '\uBCF4\uD1B5';")
lines.append("    return GestureDetector(")
lines.append("      onTap: onTap,")
lines.append("      child: Container(")
lines.append("        margin: const EdgeInsets.only(bottom: 12),")
lines.append("        padding: const EdgeInsets.all(16),")
lines.append("        decoration: BoxDecoration(")
lines.append("          color: const Color(0xFF16213E),")
lines.append("          borderRadius: BorderRadius.circular(16),")
lines.append("          border: Border.all(color: Colors.white12),")
lines.append("        ),")
lines.append("        child: Row(")
lines.append("          children: [")
lines.append("            Container(")
lines.append("              width: 48, height: 48,")
lines.append("              decoration: BoxDecoration(")
lines.append("                color: Colors.blueAccent.withValues(alpha: 0.2),")
lines.append("                borderRadius: BorderRadius.circular(12),")
lines.append("              ),")
lines.append("              child: Center(")
# 문자열 보간 포함 줄은 직접 조합
lines.append("                child: Text('$index',")
lines.append("                  style: const TextStyle(color: Colors.blueAccent, fontSize: 22, fontWeight: FontWeight.bold),")
lines.append("                ),")
lines.append("              ),")
lines.append("            ),")
lines.append("            const SizedBox(width: 16),")
lines.append("            Column(")
lines.append("              crossAxisAlignment: CrossAxisAlignment.start,")
lines.append("              children: [")
lines.append("                Text('\uD37C\uC990 $index',")
lines.append("                  style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold),")
lines.append("                ),")
lines.append("                Row(children: [")
lines.append("                  Text('${puzzle.rows}x${puzzle.cols}  |  \uC870\uAC01 ${puzzle.pieceIds.length}\uAC1C  |  ',")
lines.append("                    style: const TextStyle(color: Colors.white54, fontSize: 13),")
lines.append("                  ),")
lines.append("                  Text(diffLabel, style: TextStyle(color: diffColor, fontSize: 13)),")
lines.append("                ]),")
lines.append("              ],")
lines.append("            ),")
lines.append("            const Spacer(),")
lines.append("            const Icon(Icons.arrow_forward_ios, color: Colors.white38, size: 16),")
lines.append("          ],")
lines.append("        ),")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("}")
lines.append("")

content = "\n".join(lines)

with open('lib/screens/home_screen.dart', 'w', encoding='utf-8') as f:
    f.write(content)

# 검증
text = open('lib/screens/home_screen.dart', encoding='utf-8').read()
print(f"Lines: {len(text.splitlines())}")
print(f"Has _filterIndex: {'_filterIndex' in text}")
print(f"Has $index: {'$index' in text}")
print(f"Has puzzle.rows: {'puzzle.rows' in text}")
